# draw GUI master settings
# Per-game overrides are written here automatically as you adjust settings.
# Edit the defaults section to change settings that apply to all games.
# Consult https://www.gambit-project.org/draw/ for available settings.

defaults:
  color_scheme: colorblind
overrides:
  kuhn-4-card:
    level_scaling: 2.0
    sublevel_scaling: 0.5
    width_scaling: 0.75
    shared_terminal_depth: true
    color_scheme: colorblind
    edge_thickness: 1.6
    font_family: sffamily
    font_italic: true
    font_size: Large
    iset_fill: true
    iset_boundary: none
    iset_curved: true
    node_size: 3.1
    label_bg:
      0: true
    vary_action_label_positions: true
    vary_action_label_positions_by: level
    vary_action_label_positions_choices:
    - 4
    - 5
    - 6
    - 7
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 28
    - 13
  example:
    color_scheme: custom
    custom_colors:
      0: '#759138'
      1: '#04461b'
      2: '#DD79E0'
    iset_curved: true
    iset_curved_bend: 0.0
    iset_curved_looseness: 2.5
  jakobsen2016/fig3:
    sublevel_scaling: 0.0
    shared_terminal_depth: true
    color_scheme: gambit
    font_family: sffamily
    font_italic: true
    iset_fill: true
    iset_boundary: none
    label_bg:
      0: true
  fig12_18:
    width_scaling: 2.0
    color_scheme: colorblind
    action_label_position: 0.8
    action_label_dist: 1.5
    label_bg:
      3: true
    vary_action_label_positions: true
    vary_action_label_positions_by: player
    vary_action_label_positions_choices:
    - 3
  fig3_10:
    width_scaling: 1.6
    shared_terminal_depth: true
    color_scheme: colorblind
    vary_action_label_positions: true
    vary_action_label_positions_by: player
    vary_action_label_positions_choices:
    - 2
  fig3_17:
    shared_terminal_depth: true
    color_scheme: colorblind
    action_label_position: 0.7
  fig4_17:
    width_scaling: 1.25
    color_scheme: colorblind
    action_label_position: 0.35
  fig4_19:
    sublevel_scaling: 0.0
    shared_terminal_depth: true
    color_scheme: colorblind
    label_bg:
      0: true
    label_bg_style: white_bg
  fig4_3:
    sublevel_scaling: 0.5
    width_scaling: 1.25
    color_scheme: colorblind
    label_bg:
      3: true
    vary_action_label_positions: true
    vary_action_label_positions_by: player
    vary_action_label_positions_choices:
    - 3
  fig5_12:
    width_scaling: 0.75
    color_scheme: colorblind
    font_family: sffamily
    font_italic: true
    action_label_dist: 5.0
  cross:
    color_scheme: colorblind
    iset_curved: true
    iset_curved_bend: 50.0
    iset_curved_looseness: 3.0
  kuhn-3-card-v1:
    level_scaling: 2.4
    color_scheme: colorblind
    iset_curved: true
  tiny_hanabi:
    color_scheme: colorblind
    iset_curved: true
