# Book settings
title: draw_tree Documentation
author: The Gambit Project
logo: ""
copyright: "2023, The Gambit Project"

# Execution settings
execute:
  execute_notebooks: off

# Repository settings
repository:
  url: https://github.com/gambitproject/draw_tree
  path_to_book: docs
  branch: main

# HTML-specific settings
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true

# Sphinx configuration
sphinx:
  config:
    html_theme_options:
      navigation_with_keys: false

